version: '3'

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest #RELEASE.2022-01-27T03-53-02Z
  command: server --console-address ":9001"  http://minio{1...2}/data{1...2} 
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
  networks:
    - quokka

services:
  ### Camunda Engine ###
  camunda-engine:
    build: camunda
    ports:
      - 8080:8080
    networks:
      - quokka

  ### Error-Mitigation Service ###
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
    networks:
      - quokka
  error-mitigation-service:
    image: planqk/error-mitigation-service:v0.3.0
    command: app.py
    ports:
      - "5071:5071"
    environment:
      - MINIO_URL=nginx:9000
    depends_on:
      - nginx
    networks:
      - quokka
      
  execution-service:
    image: planqk/execution-service:v0.1.0
    build: ./services/execution-service
    ports:
      - '5075:5075'
    networks:
      - quokka
      
  optimization-service:
    image: planqk/optimization-service:v0.1.0
    build: ./services/optimization-service
    ports:
      - '5074:5074'
    networks:
      - quokka
    env_file:
     - ip.env
      
  objective-function-service:
    image: planqk/objective-function-service:v0.1.0
    ports:
      - '5072:5072'
    networks:
      - quokka
      
  circuit-generation-service:
    image: planqk/quantum-circuit-generator:v0.1.0
    ports:
      - '5073:5073'
    networks:
      - quokka

  quokka-gateway:
    image: planqk/quokka-gateway:v0.1.0
    ports:
      - '6474:6474'
    networks:
      - quokka

networks:
  quokka:
    driver: bridge

