version: '3'
services:
  execution-service:
    build: ./execution-service
    ports:
      - '5075:5075'
    networks:
      - quokka
  optimization-service:
    build: ./optimization-service
    ports:
      - '5074:5074'
    networks:
      - quokka
networks:
  quokka:
    driver: bridge
