name: Build & Tests

on:
  push:
    branches:  '**'
  pull_request:
    branches:  '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      working-directory: ./services/execution-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;
    - name: Run Tests
      working-directory: ./services/execution-service
      env:
        IBMQ_TOKEN: ${{ secrets.IBMQ_TOKEN }}
      run: |
        python -m unittest discover

